---
app_env: dev
project_name: php-app
project_root: "{{ playbook_dir | dirname }}"
nginx_conf_host_path: "{{ project_root }}/terraform/nginx.conf"
nginx_container_name: "{{ project_name }}-nginx"
php_fpm_container_name: "{{ project_name }}-php-fpm"
nginx_conf_path: /etc/nginx/conf.d/default.conf
php_web_root: /var/www/html
logrotate_path: /etc/logrotate.d/nginx
container_web_user: www-data
container_log_group: adm
temp_render_dir: "/tmp/{{ project_name }}-ansible"
nginx_listen_port: 80
php_fpm_upstream: "{{ php_fpm_container_name }}:9000"
logrotate_temp_path: /tmp/logrotate-nginx
php_temp_index_path: /tmp/index.php

