---
- name: Restart Nginx Container
  community.docker.docker_container:
    name: "{{ web_nginx_container_name }}"
    state: started
    restart: true

- name: Restart PHP-FPM Container
  community.docker.docker_container:
    name: "{{ web_php_fpm_container_name }}"
    state: started
    restart: true
