---
- name: restart nginx container
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    state: started
    restart: true

- name: restart php-fpm container
  community.docker.docker_container:
    name: "{{ php_fpm_container_name }}"
    state: started
    restart: true

